# basic options
title: Heart and Hands Blog
author: GitHub User
email: dawnann@heartandhandstraining.com
description: Discussion of Current Projects and Progress
github_username:  heartandhandstraining

# Build settings
markdown: kramdown
theme: minima
