# basic options
title: Heart and Hands Blog
name: Heart and Hands Blog
description: Computer Programming and Networking Studies
url: https://heartandhandstraining.github.io/blog/
author: GitHub User
email: dawnann@heartandhandstraining.com

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
