# basic options
title: Heart and Hands Blog
author: GitHub User
email: dawnann@heartandhandstraining.com
description: Progress Talk
github_username:  heartandhandstraining

# Build settings
markdown: kramdown
theme: minima
