# basic options
title: Heart and Hands Blogging
name: Dawn Ann Beattie, RN, MBA
description: Blogging Center
url: https://heartandhandstraining.github.io/main/blog/
author: Full-Stack Web Developer & Networking Engineer In-Training. Past Self-employed CNA/AHA Instructor, Assisted Living Administrator; Shepherd/Fiber Arts Enthusiast
email: dawnann@heartandhandstraining.com

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
