# basic options
title: Heart and Hands
name: Heart and Hands Blurbs
description: Full-Stack Web Developer & Network Engineer Trainee. Past Self-employed CNA/AHA Instructor, Assisted Living Administrator & Shepherd/Fiber Arts Enthusiast
email: dawnann@heartandhandstraining.com
url: https://heartandhandstraining.github.io/blog/
author: Dawn Ann Beattie, RN, MBA

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
