# basic options
title: Heart and Hands
name: Heart and Hands
description: Blogging Center
url: https://heartandhandstraining.github.io/main/
author: Dawn Ann Beattie, RN, MBA, Full-Stack Web Developer/Network Engineer In-Training
email: dawnann@heartandhandstraining.com

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
