# basic options
title: Heart and Hands
name: Heart and Hands
description: Computer Programming and Networking Studies
url: https://heartandhandstraining.github.io/main/
author: GitHub User
email: dawnann@heartandhandstraining.com

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
